name: Content Check

on:
  pull_request:
    paths:
      - '**/*.md'
      - '**/*.mdx'
      - 'contentlayer.config.ts'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'next.config.mjs'
      - 'postcss.config.mjs'
      - 'tailwind.config.ts'
      - 'tsconfig.json'

jobs:
  check-content:
    runs-on: ubuntu-latest
    env:
      NEXT_TELEMETRY_DISABLED: '1'
      CI: 'true'
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - run: pnpm run check:content

